# Generated by Django 4.2.3 on 2023-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_link',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
